index.html, src/badges.less, src/cards.less, src/code.less, src/colors.less, src/styles.less
Closes #11 to put cards and badges together. WIP on modern web components as #3 says.
=> Add cards and badges

src/buttons.less
This will visually update the display of focused buttons so that users
using a keyboard will differenciate them from other buttons.
You'll notice that I manually copied styles of `.shadow-hover`. I tried
```
&:focus{
border: 2px solid @secondary;
.shadow-hover;
}
```
without success.
=> Change the display of focused buttons

package-lock.json, package.json
Separated some packages that should be installed as deps and not as devDeps such as gulp and all its plugins, also with normalize.css. Theses packages would not be installed if papercss is imported in a project, this will throw an error during the `postinstall` script where papercss is trying to build the files using gulp. You can check #104 for more informations.
=> Separated devDeps with deps

.travis.yml, gulpfile.js, package-lock.json, package.json, src/normalize.less, src/reset.less, src/styles.less
PaperCSS is now modularized, this means people who are building tools using papercss can properly use it. For example, papercss/react-paper-css and papercss/vuejs-papercss can build proper component. `normalize.css` have been included in the core project `reset.less`.
=> Modularize papercss

index.html, package.json, src/modals.less
`modals.less` have missing imports, which breaks `gulp build`. This is been fixed and need to prepare papercss for 1.3.1, as said in #116. This needs to be merged ASAP.
Waiting for @rhyneav to prepare for 1.3.1. Once you have added your commits, this can be merged without any errors/problems.
=> Fix for missing imports in modals.less

src/components/_accordion.scss, src/components/_buttons.scss, src/components/_modals.scss, src/components/_popovers.scss, src/core/_config.scss
Unified the transition styles across components with `@mixin transition()`
To unify the transitions of components https://github.com/papercss/papercss/pull/126 introduced a new mixin.
I checked every component and changed those transitions to use this mixin.
=> Unified transitions

src/components/_cards.scss, src/core/_config.scss
This should fix the bug described in https://github.com/papercss/papercss/issues/111
I added the [`will-change: transform`](https://dev.opera.com/articles/css-will-change-property/) and [`backface-visibility: hidden`](https://css-tricks.com/almanac/properties/b/backface-visibility/)  directives to the `.cards` component.
tl;dr
> The will-change property allows you to inform the browser ahead of time of what kinds of changes you are likely to make to an element, so that it can set up the appropriate optimizations before they’re needed, therefore avoiding a non-trivial start-up cost which can have a negative effect on the responsiveness of a page. **The elements can be changed and rendered faster, and the page will be able to update snappily, resulting in a smoother experience.** …
=> hotfix-animationbug

README.md
Fixed a typo in the readme.
- [X ] I certify that these changes according to the Developer Certificate of Origin 1.1 as described at <https://developercertificate.org/>.
=> Fixing typo.

.stylelintrc.json, .travis.yml, gulpfile.js, package-lock.json, package.json, src/components/_accordion.scss, src/components/_alerts.scss, src/components/_article.scss, src/components/_badges.scss, src/components/_buttons.scss, src/components/_cards.scss, src/components/_forms.scss, src/components/_modals.scss, src/components/_navbar.scss, src/components/_popovers.scss, src/components/_tabs.scss, src/components/_utilities.scss, src/content/_code.scss, src/content/_fonts.scss, src/content/_images.scss, src/content/_lists.scss, src/content/_tables.scss, src/core/_config.scss, src/core/_reset.scss, src/layout/_container.scss, src/layout/_flexbox.scss, src/utilities/_shadows.scss
Added stylelint to keep the SCSS clean and beautiful. Current SCSS has been refactored to adhere to the linter as well. So, a lot of files have been changed, but the end result has not changed.
Sample linting output:
It uses "stylelint-config-sass-guidelines" as the default and the following rules have been disabled:
- **property-no-vendor-prefix** => We use vendor prefixes in some instances. We should eventually refactor to just let SCSS do this for us.
- **value-no-vendor-prefix** => Same as above.
- **selector-no-qualifying-type** => Since a lot of styles are implicit, we use some funky selectors.
- **selector-max-compound-selectors** => We select deep since a lot of styles are implicit.
- **scss/selector-no-redundant-nesting-selector** => We use nested for the radio buttons and check …
=> Feature linter

.browserslistrc, .stylelintrc.json, gulpfile.js, package-lock.json, package.json, src/components/_buttons.scss, src/components/_modals.scss, src/components/_navbar.scss, src/core/_config.scss, src/layout/_container.scss, src/layout/_flexbox.scss
Use Gulp Autoprefixer instead of manually adding vendor prefixes.
...
* A .browserslintrc file has been added so we can specify what browsers are supported. This is used by Autoprefixer to add the relevant prefixes and remove redundant ones.
* The "property-no-vendor-prefix" and "value-no-vendor-prefix" have been removed from .stylelintrc.json. The prefixes are automatically added so they needn’t be in the .scss files.
* The translate mixin has been removed as this change has made it redundant.
=> Use gulp autoprefixer

src/components/_forms.scss
Fix for https://github.com/papercss/papercss/issues/162.
...
Simple fix required inputs having a property `opacity: 0;` instead of `display: none;`.
=> Keyboard control on radio buttons bug fix

src/components/_progress.scss
It seems like progress bar percentage calculation doesn't work with sass-loader.
None
I've got this issue while trying to use sass files with Symfony Encore and sass-loader (based on Webpack).
```
D:\projets\ansible-vagrant\html\www.symfony.vbox>yarn encore dev
yarn run v1.9.4
$ D:\projets\ansible-vagrant\html\www.symfony.vbox\node_modules\.bin\encore dev
Running webpack ...
ERROR  Failed to compile with 1 errors                                                                                                                                                                                              22:57:03
error  in ./assets/css/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from …
```
=> Fix percentage calculation in progress bar for loop

src/components/_buttons.scss
.paper-btn anchor are not playing hover transition.
You can reproduce on https://www.getpapercss.com/docs/components/buttons/. When hovering buttons, they go slightly down, but when hovering links, they don't.
Changing `display: inline` to `display: inline-block` fixes the issue.
=> Fix hover transition on .paper-btn anchors

docs/content/docs/content/lists.md
It's a common mistake, but HTML lists should be nested so that a list is in between the opening and closing tags for a given list item. I've corrected it in these examples. Most browsers handle it fine but it's best to use correct HTML, just in case there's a browser or platform that doesn't parse it correctly.
=> Fixed markup for nested lists

docs/content/about.md
Link to the project license was fixed in the "About" page.
=> Fix link to License in About page

src/components/_tabs.scss
Fixes Bug where the content would be aligned right next to the tabs on larger screens.
See: https://github.com/papercss/papercss/issues/202
=> Tabs Content Alignment Bugfix

docs/content/docs/components/forms.md, src/components/_forms.scss
Add style for the range sliders, overriding the track and the thumb in order to look the same on most of browsers (tested on Chrome, Firefox and IE).
See Issue #210 
Ressources :
- https://css-tricks.com/styling-cross-browser-compatible-range-inputs-css/
- https://www.w3schools.com/howto/howto_js_rangeslider.asp
=> Feature: Paper style for range sliders

CONTRIBUTING.md, README.md
Closes #229 
Updates `readme.md` and `contributing.md` to explain new way of building. It used to be with `gulp`, but now there is `build/build.js`. Also changes the contributing steps slightly by including the `npm run css:build` step and explaining more about what `npm run start` does.
=> Updated docs

package-lock.json, package.json
Running `npm audit` showed a lot of vulnerabilities, which all came from packages that `stylelint` depended on.
- Updated `stylelint` to reduce vulnerabilities to `0`
- Updated `stylelint-config-standard` to a version compatible with latest `stylelint` version
- Updated `stylelint-order` to a version compatible with latest `stylelint` version
- Updated `stylelint-scss` to a version compatible with latest `stylelint` version
- Updated npm `stylelint` command. Removed the quotes that surrounded the scss files path because it didn't work with the quotes anymore.
Doing `npm run stylelint` results in 2 deprecation warning errors. These are errors about style rules.
I tried running `npm run stylelint` from the `master` branch, and it resulted in the error: `Error: No files matching the pattern …
=> Update vulnerable npm packages

src/core/_config.scss
The PR adds a change in the _config.scss file to enable font-display: swap.  This instructs browsers to use the fallback font to display the text until the custom font has fully downloaded. Also helps with performance so you get that 100 score on lighthouse 😁
...
...
This PR closes #260 
...
=> Enable "font-display: swap " to avoid showing invisible text

src/components/_forms.scss
Set a background color for select elements as options was unreadable with dark mode.
Before: 
After:
=> set select background color

src/components/_popovers.scss
This PR is intended to fix #297, such that popovers do not appear when hovering over the area occupied by the (still invisible) popover. This can be important if other elements are beneath that area, and also [improves accessibility](https://css-tricks.com/snippets/css/toggle-visibility-when-hiding-elements/).
Unfortunately I'm having trouble getting the local development server running to test this change. In CONTRIBUTING.md I don't see anything about installing Hugo — do I need to do anything manually there? I'm on macOS. When running `npm run dev` I get errors like "node_modules/hugo-bin/vendor EACCES", or when installing Hugo manually and running ` hugo server --source=docs --disableFastRender` I get the error:
> `Configured defaultMarkdownHandler "blackfriday" not found. Did you mean …
=> Set visibility of popovers, avoid trigger when hovering invisible pseudoelement
