index.html
src/popovers.less
src/styles.less

First step of adding *modern components* such as popovers, as said in #3.
[GIF preview here](https://i.imgur.com/Vm61PBM.gifv).

Popovers added

---

index.html
src/borders.less

I have added the border styles of dashed, dotted and thick.

Adding more border styles, dashed, dotted, thick

---

README.md
src/borders.less
src/colors.less

Refactored colours to make them more dynamic 
I have also updated the README file to show how new colours can be added

 Refactored colours to make them more dynamic 

---

index.html
src/buttons.less
src/forms.less

Adding disbaled styling for inputs

---

PULL_REQUEST_TEMPLATE.md

Checkbox to get DCO for each contribution
Some links for reference:
- <https://developercertificate.org/>
- <https://oss.kemitchell.com/#contribution-management>
- <https://github.com/choojs/discuss/issues/3>, with some additional resources
- <https://lwn.net/Articles/592503/>

Pull request template to get DCO (Developers Certificate of Origin)

---

index.html
src/colors.less
src/popovers.less

I merged the position attribute into the popover attribute, achieving the same results using only 1 attribute instead of 2. Updated demo as well.
...
If there are plans the extend popover features further (more attributes) then this is not a good solution. In case the plan is to keep it as simple as it is now, it's viable.
...

Feature short popover attributes

---

index.html

Fixes #41 
;)
Update HTTP to HTTPS in an image

update image to https

---

index.html

there was a mistake which said "flex-right" instead of "flex-center" on line 167 and i corrected it
N/A

corrected flex-center alignment on line 167

---

index.html
src/fonts.less
src/forms.less

This is regarding issue Feature: Textarea in forms #42
Added the support for textarea making it usable out of the box with papercss styling
Also added the documentation and usage code on index.html

Feature textarea

---

index.html

Regarding issue Cards =/= Colors #47

Hotfix summary links

---

src/forms.less

fix position value

---

index.html

Add IDs to inputs and selects and reference them in their respective labels.

Add IDs to inputs and selects

---

.editorconfig
README.md

As #54 says, we need an `.editorconfig` file because everyone is using its own indentation size and type, add/remove EOL in files. To make sure these changes are effective, use an `editorconfig` plugin/addon on your IDE. For example in Atom there is the [editorconfig package](https://atom.io/packages/editorconfig), as well for [Sublime](https://github.com/sindresorhus/editorconfig-sublime), [VS Code](https://github.com/editorconfig/editorconfig-vscode), [Vim](https://github.com/editorconfig/editorconfig-vim), ...

Added a basic .editorconfig

---

index.html
src/article.less
src/styles.less

The article component consists of the article itself, a title and meta data.
...

Feature article

---

README.md
index.html
src/tables.less

The x-axis overflow issue #52 is fixed in this commit
Added media query for reduced padding in mobile for table and separated paper div from container

Fix for overflow x-axis in mobile view

---

index.html
src/lists.less

Add the capability of the list to be listed inline/horizontal. Useful for menu item
...
...
Could be added more styling in the future
...

added class for inline list

---

index.html

Fixing typo in html.
...
...
...

Imprefect Buttons -> Imperfect Buttons

---

tests/colors.js

Adding more tests for the color less file
Closes #91

Tests for colors

---

.travis.yml

Remove laucher from travis setup

---

README.md

shouts outs? shouts out? shout out?

---

index.html
src/components/_accordion.scss
src/core/_config.scss

Changed and moved `@mixin transition()` into `/core/_config.scss` and cleaned up `_accordion.scss`
To build on top of the changes that came with the SCSS port I moved the mixin into `/core/_config.scss`. This way the mixin can be used from anywhere. I also refactored it so you can basically use it for every transition you may need.
```scss
@mixin transition($name:all, $duration:235ms, $animation:ease-in-out, $delay:0s){
-webkit-transition: $name $duration $animation $delay;
-moz-transition: $name $duration $animation $delay;
-o-transition: $name $duration $animation $delay;
transition: $name $duration $animation $delay;
}
```
If you include it without passing any parameters it will output the following CSS:
```scss
// Input
.transition-me {
@include transition;
}
// Output
.transition-me …
```

Accordion fix

---

README.md

Tiny PR to fix the issue with a broken link in the `readme.md`

Fixed typo in the url

---

gulpfile.js
package-lock.json
package.json

gulp-sass needed for production install
no documentation for production install so hugo-bin is not needed
Fixes #132
...
- [X ] I certify that these changes according to the Developer Certificate of Origin 1.1 as described at <https://developercertificate.org/>.

gulp-sass needed for production install

---

LICENSE.md

- Filename matches format of other standard files in the repo (README, etc.)
- Include title and copyright notice per the template text:
- https://choosealicense.com/licenses/isc/
- https://opensource.org/licenses/isc-license
- https://spdx.org/licenses/ISC.html#licenseText

standardize license file

---

docs/content/docs/components/alerts.md
src/components/_alerts.scss

Created dismissible alerts.
Tested in Chrome, Firefox, Safari and Opera.

Feature dismissible alerts

---

README.md

A few grammar errors and punctuation mistakes have been rectified.
...
...

Grammer Errors in Readme

---

README.md

Fix yarn install command documentation
None
None

Fix yarn install command documentation

---

docs/content/docs/components/buttons.md
package.json
src/components/_buttons.scss
src/core/_config.scss

Outline buttons

---

docs/content/docs/components/forms.md
package.json
src/components/_forms.scss

Switch components.
Issue: [Switch component #121](https://github.com/papercss/papercss/issues/121)
2x2+1 variable styled switches.
- Default inline switch style with square and circle form. (first 4 row)
- Default outline switch style with square and circle form. (second 4 row)
- Tile styled switches. (last row)

Switch components

---

docs/content/docs/components/navbar.md
package.json
src/components/_navbar.scss

Navbar fix for FireFox

---

docs/content/docs/components/breadcrumb.md
package-lock.json
package.json
src/components/_breadcrumb.scss
src/components/_navbar.scss
src/styles.scss

Sipmle breadcrumb.
One of ["Missing" elements suggestion](https://github.com/papercss/papercss/issues/62)

Feature Breadcrumb

---

docs/content/_index.md

Fix styling of word GitHub

---

src/components/_tabs.scss

Hi, first of all thank you for your cool framework. I really have fun working with it :)
I'm building an app for building flashcard sets in which I decided to use tabs component for switching between different languages. However I've noticed that current version assumes that there'll only be a single tab component on the page.
I overcame it in my project by changing `=` (attribute equals) selector to `$=` (attribute ends with) selector. 
This allows me to generate different tab IDs for different flashcards, like this:
```ruby
<% tab_name = "tabs_#{word.id}" %>
<% tab1_id = "#{tab_name}_tab1" %>
<% tab2_id = "#{tab_name}_tab2" %>
<div class="xs-12 sm-6 md-4 lg-3 col align-top flashcard-column">
<div class="card">
<div class="card-body">
<div class="row tabs">
<input id="<%= tab1_id %>" …
```

Support multiple tab components

---

docs/content/docs/components/forms.md

I simply fixed some minor HTML errors in `forms.md`

Correct minor errors in forms.md

---

package-lock.json
package.json

Resolves #214 
Changes `gulp-clean-css` version in `package.json`.
...
...
More information at #214

Hotfix: update clean css

---

src/core/_config.scss

Closes #191 
Added a variable in scss called `$font-src`. It can be changed to change the font import url. It can be disabled by setting it to a falsy value.

Change or disable font src

---

src/components/_navbar.scss

Descriptions is given by #243 
This PR, if merged, closes #243

fix: Re-added height to navbar icon bars
